[theme]
primaryColor = "#7EB900"             # 버튼/체크박스 등 포커스 색
backgroundColor = "#FFFFFF"          # 메인 배경
secondaryBackgroundColor = "#F1F3F3" # 사이드바 배경
textColor = "#1C1C1C"                # 글자색
font = "sans serif"
